tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "puppetlabs/puppet"
cask "alfred"
cask "anydesk"
cask "caffeine"
cask "discord"
cask "docker"
cask "github"
cask "google-drive"
cask "google-chrome"
cask "iterm2"
cask "remote-desktop-manager"
cask "spotify"
cask "zoomus"
mas "1Password 7", id: 1333542190
mas "The Unarchiver", id: 425424353
